// Generated by CoffeeScript 1.8.0
(function() {
  $(function() {
    return $('.slick-slideshow').slick({
      autoplay: true,
      autoplaySpeed: 3000,
      arrows: true,
      draggable: false,
      fade: true,
      swipe: false
    });
  });

}).call(this);
